#!/bin/bash
pip install bash_kernel numpy matplotlib h5py scipy

python -m bash_kernel.install

git clone https://github.com/mrirecon/bart/
cd bart
git checkout d2896b04cb9a0b69c4ec26bbf790d73fcce29638
CC=gcc-12 make -j
cd ..

